site_name: OpenICU
docs_dir: docs
nav:
  - Getting Started:
      - Package Overview: "getting_started/overview.md"
      - Installation: "getting_started/installation.md"
      - Basic Usage: "getting_started/basic_usage.md"
      - Contributing: "getting_started/contributing.md"
  # - User Guide:
  - API Reference: reference/

copyright: Copyright &copy; 2023 AIDH MS

theme:
  name: material
  repo_url: "https://github.com/aidh-ms/OpenICU"
  features:
    - navigation.tabs
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aidh-ms/OpenICU
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ # TODO change this to your project name

extra_css:
  - assets/css/code_select.css
  - assets/css/fonts.css

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.extra
  - footnotes
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search:
  - macros:
      include_dir: ./
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: ["open_icu"]
          options:
            docstring_style: google
