[tool.poetry]
name = "open_icu"
description = "This is a project to unify and analyse data from different ICU data sources."
version = "1.0.0"
license = "MIT"
authors = ["ADIH MS"]
readme = "README.md"
homepage = "https://github.com/aidh-ms/OpenICU"
repository = "https://github.com/aidh-ms/OpenICU"
documentation = "https://github.com/aidh-ms/OpenICU"
keywords = ["Data", "ICU", "Healthcare", "Analysis"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.urls]
Changelog = "https://github.com/aidh-ms/OpenICU/releases"
Bugtracker = "https://github.com/aidh-ms/OpenICU/issues"

[tool.poetry.dependencies]
python = "^3.13"

[tool.poetry.group.dev.dependencies]
mypy = "^1.14.0"
pytest = "^8.0.2"
coverage = "^7.6.10"
pytest-cov = "^6.0.0"
ruff = "^0.8.4"
pytest-asyncio = "^0.25.0"
pytest-recording = "^0.13.1"
pytest-random-order = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
strict_optional = true

[tool.pytest.ini_options]
python_files = ["test_*.py", "*_test.py"]
filterwarnings = ["ignore::DeprecationWarning"]
asyncio_mode = "auto"
addopts = [
    "--cov",
    "--cov-branch",
    "--cov=src",
    "--cov-report=xml",
    "--import-mode=importlib",
    "--random-order",
]
