name: eicu
version: "2.0"
tables:
  - name: patient
    path: patient.csv
    fields:
      # general code
      - field: source_db_code
        type: string
        constant: eicu
      - field: source_table_code
        type: string
        constant: patient
      # codes
      - field: admissionheight_code
        type: string
        constant: HEIGHT
      - field: admissionweight_code
        type: string
        constant: ADMISSION_WEIGHT
      - field: age_code
        type: string
        constant: AGE
      - field: dischargeweight_code
        type: string
        constant: DISCHARGE_WEIGHT
      - field: ethnicity_code
        type: string
        constant: ETHNICITY
      - field: gender_code
        type: string
        constant: GENDER
      - field: in_code
        type: string
        constant: ICU_ADMISSION
      - field: out_code
        type: string
        constant: icu_discharge
      # subject_id and extensions
      - field: hadm_id
        type: int64
        constant: -1
      - field: patienthealthsystemstayid
        type: int64
      - field: patientunitstayid
        type: int64
      - field: row_id
        type: int64
      # db fields
      - field: admission_timestamp
        year:
          field: hospitaldischargeyear
          type: int64[pyarrow]
        month:
          field: month
          type: int64[pyarrow]
          constant: 1
        day:
          field: day
          type: int64[pyarrow]
          constant: 1
        time:
          field: hospitaladmittime24
          type: string
        offset:
          field: hospitaladmitoffset
          type: int64
      - field: admissionheight
        type: float32
      - field: admissionheight_unit
        type: string
        constant: cm
      - field: admissionweight
        type: float32
      - field: age_unit
        type: string
        constant: y
      - field: apacheadmissiondx
        type: string
      - field: categoric_age
        type: string
      - field: discharge_timestamp
        base:
          field: admission_timestamp
          type: datetime
        offset:
          field: unitdischargeoffset
          type: int64
      - field: dischargeweight
        type: float32
      - field: ethnicity
        type: string
      - field: gender
        type: string
      - field: hospitaladmitsource
        type: string[pyarrow]
      - field: hospitaldischargelocation
        type: string[pyarrow]
      - field: hospitalid
        type: int64
      - field: numeric_age
        type: int64[pyarrow]
      - field: unitadmitsource
        type: string[pyarrow]
      - field: unitstaytype
        type: string[pyarrow]
      - field: unitvisitnumber
        type: int64
      - field: unittype
        type: string
      - field: uniquepid
        type: string
      - field: wardid
        type: int64
      - field: weight_unit
        type: string
        constant: kg
    events:
      - name: icu_admission
        fields:
          subject_id: patienthealthsystemstayid
          time: admission_timestamp
          code:
            - in_code
            - unittype
        extension:
          hadm_id: hadm_id
          stay_id: patientunitstayid
          row_id: row_id
      - name: icu_discharge
        fields:
          subject_id: patienthealthsystemstayid
          time: discharge_timestamp
          code:
            - out_code
            - unittype
        extension:
          hadm_id: hadm_id
          stay_id: patientunitstayid
          row_id: row_id
      - name: gender
        fields:
          subject_id: patienthealthsystemstayid
          # maybe change time to birthdate
          time: admission_timestamp 
          code: # code is null, when using gender and gender is empty string 
            - gender_code
            - gender 
        extension:
          hadm_id: hadm_id
          stay_id: patientunitstayid
          row_id: row_id
      - name: age
        fields:
          subject_id: patienthealthsystemstayid
          time: admission_timestamp
          code:
            - age_code
            - age_unit
          numeric_value: numeric_age
          text_value: categoric_age
        extension:
          hadm_id: hadm_id
          stay_id: patientunitstayid
          row_id: row_id
      - name: ethnicity
        fields:
          subject_id: patienthealthsystemstayid
          # maybe change time to birthdate
          time: admission_timestamp
          code:
            - ethnicity_code
          text_value: ethnicity
        extension:
          hadm_id: hadm_id
          stay_id: patientunitstayid
          row_id: row_id
      - name: admissionheight
        fields:
          subject_id: patienthealthsystemstayid
          time: admission_timestamp
          code:
            - admissionheight_code
            - admissionheight_unit
          numeric_value: admissionheight
        extension:
          hadm_id: hadm_id
          stay_id: patientunitstayid
          row_id: row_id
      - name: dischargeweight
        fields:
          subject_id: patienthealthsystemstayid
          time: discharge_timestamp
          code: 
            - dischargeweight_code
            - weight_unit
          numeric_value: dischargeweight
        extension:
          hadm_id: hadm_id
          stay_id: patientunitstayid
          row_id: row_id
      - name: admissionweight
        fields:
          subject_id: patienthealthsystemstayid
          time: admission_timestamp
          code: 
            - admissionheight_code
            - admissionheight_unit
          numeric_value: admissionweight
        extension:
          hadm_id: hadm_id
          stay_id: patientunitstayid
          row_id: row_id

  - name: vitalPeriodic
    path: vitalPeriodic.csv
    fields:
      # general code
      - field: source_db_code
        type: string
        constant: eicu
      - field: source_table_code
        type: string
        constant: vitalPeriodic
      # codes
      - field: heartrate_code
        type: string
        constant: HEART_RATE//BPM
      # subject_id and extensions
      - field: patientunitstayid
        type: int64
      - field: row_id
        type: int64
      # db fields
      - field: event_timestamp
        base:
          field: admission_timestamp
          type: datetime
        offset:
          field: observationoffset
          type: int64
      - field: heartrate
        type: float32
    join:
      - name: patient
        path: patient.csv
        fields:
        # general code
          - field: hadm_id
            type: int64
            constant: -1
          - field: patienthealthsystemstayid
            type: int64
          - field: patientunitstayid
            type: int64
        # codes
        # subject_id and extensions
        # db fields
          - field: admission_timestamp
            year:
              field: hospitaldischargeyear
              type: int64[pyarrow]
            month:
              field: month
              type: int64[pyarrow]
              constant: 1
            day:
              field: day
              type: int64[pyarrow]
              constant: 1
            time:
              field: hospitaladmittime24
              type: string
            offset:
              field: hospitaladmitoffset
              type: int64
        both_on:
          - patientunitstayid
    events:
      - name: heartrate
        fields:
          subject_id: patienthealthsystemstayid
          time: event_timestamp
          code:
            - source_db_code
            - source_table_code
            - heartrate_code
          numeric_value: heartrate
        extension:
          hadm_id: hadm_id
          stay_id: patientunitstayid
          row_id: row_id

  - name: infusionDrug
    path: infusionDrug.csv
    fields:
      # general code
      - field: source_db_code
        type: string
        constant: eicu
      - field: source_table_code
        type: string
        constant: infusionDrug
      # codes
      # subject_id and extensions
      - field: patientunitstayid
        type: int64
      - field: row_id
        type: int64
      # db fields
      - field: drugamount
        type: float32
      - field: drugname
        type: string
      - field: event_timestamp
        base:
          field: admission_timestamp
          type: datetime
        offset:
          field: infusionoffset
          type: int64
    join:
      - name: patient
        path: patient.csv
        fields:
          # general code
          # codes
          # subject_id and extensions
          - field: hadm_id
            type: int64
            constant: -1
          - field: patienthealthsystemstayid
            type: int64
          - field: patientunitstayid
            type: int64
          # db fields
          - field: admission_timestamp
            year:
              field: hospitaldischargeyear
              type: int64[pyarrow]
            month:
              field: month
              type: int64[pyarrow]
              constant: 1
            day:
              field: day
              type: int64[pyarrow]
              constant: 1
            time:
              field: hospitaladmittime24
              type: string
            offset:
              field: hospitaladmitoffset
              type: int64
        both_on:
          - patientunitstayid
    events:
      - name: drugamount
        fields:
          subject_id: patienthealthsystemstayid
          time: event_timestamp
          code:
            - source_db_code
            - source_table_code
            - drugname
          numeric_value: drugamount
          extension:
            hadm_id: hadm_id
            stay_id: patientunitstayid
            row_id: row_id
