name: mimic
version: "3.1"
tables:
  - name: medications
    path: icu/inputevents.csv
    fields:
      # general code
      - field: source_db_code
        type: string
        constant: mimic 
      - field: source_table_code
        type: string
        constant: icu/inputevents
      # codes
      - field: caregiver_store_code
        type: string
        constant: CG_ST # caregiver_storetime
      - field: continueinnextdept_code
        type: string
        constant: CONTINUE_IN_NEXT_DEPT
      - field: isopenbag_code
        type: string
        constant: ISOPENBAG
      - field: linkorder_code
        type: string
        constant: LINKORDER
      - field: order_code
        type: string
        constant: ORDER
      - field: originalamount_code
        type: string
        constant: ORIGINAL_DOSAGE
      - field: originalrate_code
        type: string
        constant: ORIGINALRATE
      - field: rate_end_code
        type: string
        constant: RATE_END
      - field: rate_start_code
        type: string
        constant: RATE_START
      - field: statusdescription_code
        type: string
        constant: STATUSDESCRIPTION
      - field: totalamount_code
        type: string
        constant: TOTALAMOUNT
      - field: weight_code
        type: string
        constant: WEIGHT 
      # subject_id and extentions
      - field: hadm_id
        type: int64
      - field: row_id
        type: int64
      - field: stay_id
        type: int64
      - field: subject_id
        type: int64
      # db fields
      - field: amount
        type: float32
      - field: amountuom
        type: string
      - field: caregiver_id
        type: int64
      - field: continueinnextdept
        type: int64
      - field: endtime
        type: datetime
      - field: isopenbag
        type: int64
      - field: itemid
        type: int64
      - field: linkorderid
        type: int64
      - field: ordercategoryname
        type: string
      - field: ordercategorydescription
        type: string
      - field: ordercomponenttypedescription
        type: string
      - field: orderid
        type: int64
      - field: originalamount
        type: float32
      - field: originalrate
        type: float32
      - field: patientweight
        type: int64[pyarrow]
      - field: rate
        type: float32
      - field: rateuom
        type: string
      - field: secondaryordercategoryname
        type: string
      - field: starttime
        type: datetime
      - field: statusdescription
        type: string
      - field: storetime
        type: datetime
      - field: totalamount
        type: float32[pyarrow]
      - field: totalamountuom
        type: string
      - field: weightuom
        type: string
        constant: kg
    join:
      - name: d_items
        path: icu/d_items.csv
        fields:
          - field: itemid
            type: int64
          - field: label
            type: string
        both_on:
          - itemid
    base_extension:
      hadm_id: hadm_id
      stay_id: stay_id
      row_id: row_id
    events:
      - name: dosage
        fields:
          subject_id: subject_id
          time: endtime
          code:
            - source_db_code
            - source_table_code
            - label
            - amountuom
          numeric_value: amount
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      # changes noted but maybe overwriten again
      - name: rate_start
        fields:
          subject_id: subject_id
          time: starttime
          code:
            - source_db_code
            - source_table_code
            - label
            - rateuom
            - rate_end_code
          numeric_value: rate
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
        filters:
          dropna:
            - rate
      # changes noted but maybe overwriten again
      - name: rate_end
        fields:
          subject_id: subject_id
          time: endtime
          code:
            - source_db_code
            - source_table_code
            - label
            - rateuom
            - rate_start_code
          numeric_value: rate
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
        filters:
          dropna:
            - rate
      - name: caregiver_store
        fields: 
          subject_id: subject_id
          time: storetime
          code: 
            - source_db_code
            - source_table_code
            - caregiver_store_code
          numeric_value: caregiver_id
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      - name: weight
        fields:
          subject_id: subject_id
          time: starttime
          code:
            - source_db_code
            - source_table_code
            - weight_code
            - weightuom
          numeric_value: patientweight
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
        filters:
          dropna:
            - patientweight
      - name: totalamount
        fields:
          subject_id: subject_id
          time: endtime
          code:
            - source_db_code
            - source_table_code
            - totalamount_code
            - totalamountuom 
          numeric_value: totalamount
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
        filters:
          dropna:
            - totalamount
      - name: order
        fields: 
          subject_id: subject_id
          time: endtime
          code: 
            - source_db_code
            - source_table_code
            - order_code
            - ordercategoryname # (!!!) 
            - secondaryordercategoryname  # (!!!)
            # - ordercomponenttypedescription # (!!!)
            # - ordercategorydescription  # (!!!)
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      - name: linkorder
        fields: 
          subject_id: subject_id
          time: endtime
          code: 
            - source_db_code
            - source_table_code
            - linkorder_code
          numeric_value: linkorderid
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      - name: isopenbag
        fields: 
          subject_id: subject_id
          time: starttime
          code:
            - source_db_code
            - source_table_code
            - isopenbag_code
          numeric_value: isopenbag
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      - name: continueinnextdept
        fields:
          subject_id: subject_id
          time: endtime
          code: 
            - source_db_code
            - source_table_code
            - continueinnextdept_code
          numeric_value: continueinnextdept
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      - name: statusdescription
        fields:
          subject_id: subject_id
          time: endtime
          code: 
            - source_db_code
            - source_table_code
            - statusdescription_code
            - statusdescription
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      - name: originalamount
        fields:
          subject_id: subject_id
          time: starttime
          code: 
            - source_db_code
            - source_table_code
            - originalamount_code
            - label
            - amountuom
          numeric_value: originalamount
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      - name: originalrate
        fields:
          subject_id: subject_id
          time: starttime
          code:
            - source_db_code
            - source_table_code
            - originalrate_code
            - label
            - rateuom
          numeric_value: originalrate
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
        filters:
          dropna:
            - originalrate

  - name: chartevents
    path: icu/chartevents.csv
    fields:
      # general code
      - field: source_db_code
        type: string
        constant: mimic 
      - field: source_table_code
        type: string
        constant: icu/chartevents
      # codes
      - field: caregiver_store_code
        type: string
        constant: CG_ST
      - field: chartevent_code
        type: string
        constant: CHARTEVENT
      - field: warning_code
        type: string
        constant: WARNING
      # subject_id and extentions
      - field: hadm_id
        type: int64
      - field: row_id
        type: int64
      - field: stay_id
        type: int64
      - field: subject_id
        type: int64
      # db fields
      - field: charttime
        type: datetime
      - field: caregiver_id
        type: int64[pyarrow]
      - field: itemid
        type: int64
      - field: storetime
        type: datetime
      - field: value
        type: string
      - field: valuenum
        type: float32
      - field: valueuom
        type: string
      - field: warning
        type: int64[pyarrow]
    join:
      - name: d_items
        path: icu/d_items.csv
        fields:
          - field: itemid
            type: int64
          - field: label
            type: string
        both_on:
          - itemid
    events:
      - name: chartevent
        fields:
          subject_id: subject_id
          time: charttime
          code:
            - source_db_code
            - source_table_code
            - chartevent_code
            - label
            - valueuom
          numeric_value: valuenum
          text_value: value
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      - name: caregiver_store
        fields:
          subject_id: subject_id
          time: storetime
          code: 
            - source_db_code
            - source_table_code
            - caregiver_store_code
          numeric_value: caregiver_id
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
        filters:
          dropna: 
            - caregiver_id
      - name: warning
        fields:
          subject_id: subject_id
          time: storetime
          code:
            - source_db_code
            - source_table_code
            - warning_code
          numeric_value: warning
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
        filters:
          dropna:
            - warning

  - name: icustays
    path: icu/icustays.csv
    fields:
      # General code
      - field: source_db_code
        type: string
        constant: mimic
      - field: source_table_code
        type: string
        constant: icu/icustays

      # codes
      - field: in_code
        type: string
        constant: ICU_ADMISSION
      - field: los_code
        type: string
        constant: ICU_LENGTH_OF_STAY
      - field: los_code
        type: string
        constant: ICU_LOS
      - field: out_code
        type: string
        constant: ICU_DISCHARGE

      # subject_id and extentions
      - field: hadm_id
        type: int64
      - field: row_id
        type: int64
      - field: stay_id
        type: int64
      - field: subject_id
        type: int64

      # db fields
      - field: first_careunit
        type: string
      - field: intime
        type: datetime
      - field: last_careunit
        type: string
      - field: los
        type: float32
      - field: los_unit
        type: string
        constant: d
      - field: outtime
        type: datetime
    events:
      - name: icu_admission
        fields:
          subject_id: subject_id
          time: intime
          code:
            - source_db_code
            - source_table_code
            - in_code
            - first_careunit
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      - name: icu_discharge
        fields:
          subject_id: subject_id
          time: outtime
          code:
            - source_db_code
            - source_table_code
            - out_code
            - last_careunit
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
      - name: icu_length_of_stay
        fields:
          subject_id: subject_id
          time: outtime
          code:
            - source_db_code
            - source_table_code
            - los_code
            - los_unit
          numeric_value: los
        extension:
          hadm_id: hadm_id
          stay_id: stay_id
          row_id: row_id
