name: mimic
version: "3.1"
tables:
  - name: medications
    path: icu/inputevents.csv
    fields:
      - field: source_db_code
        type: string
        constant: mimic 
      - field: source_table_code
        type: string
        constant: icu/inputevents
      - field: subject_id
        type: int64
      - field: hadm_id
        type: int64
      - field: stay_id
        type: int64
      - field: row_id
        type: int64
      - field: endtime
        type: datetime
      - field: amount
        type: float32
      - field: amountuom
        type: string
      - field: rate_start_code
        type: string
        constant: RATE_START
      - field: starttime
        type: datetime
      - field: rate_end_code
        type: string
        constant: RATE_END
      - field: endtime
        type: datetime
      - field: rateuom
        type: string
      - field: rate
        type: float32
      - field: itemid
        type: int64
      - field: caregiver_store_code
        type: string
        constant: CG_ST # caregiver_storetime
      - field: caregiver_id
        type: int64
      - field: storetime
        type: datetime
    join:
      - name: d_items
        path: icu/d_items.csv
        fields:
          - field: itemid
            type: int64
          - field: label
            type: string
        both_on:
          - itemid
    events:
      - name: dosage
        fields:
          subject_id: subject_id
          time: endtime
          code:
            - label
            - amountuom
          numeric_value: amount
          extension:
            hadm_id: hadm_id
            stay_id: stay_id
            row_id: row_id
      - name: rate_start
        fields:
          subject_id: subject_id
          time: starttime
          code:
            - label
            - rateuom
            - rate_end_code
          numeric_value: rate
          extension:
            hadm_id: hadm_id
            stay_id: stay_id
            row_id: row_id
        filters:
          dropna:
            - rate
      - name: rate_end
        fields:
          subject_id: subject_id
          time: endtime
          code:
            - label
            - rateuom
            - rate_start_code
          numeric_value: rate
          extension:
            hadm_id: hadm_id
            stay_id: stay_id
            row_id: row_id
        filters:
          dropna:
            - rate
      - name: caregiver_store
        fields: 
          subject_id: subject_id
          time: storetime
          code: 
            - caregiver_store_code
          numeric_value: caregiver_id
          extension:
            hadm_id: hadm_id
            stay_id: stay_id
            row_id: row_id

  - name: chartevents
    path: icu/chartevents.csv
    fields:
      - field: subject_id
        type: int64
      - field: hadm_id
        type: int64
      - field: stay_id
        type: int64
      - field: row_id
        type: int64
      - field: charttime
        type: datetime
      - field: value
        type: string
      - field: valuenum
        type: float32
      - field: valueuom
        type: string
      - field: itemid
        type: int64
    join:
      - name: d_items
        path: icu/d_items.csv
        fields:
          - field: itemid
            type: int64
          - field: label
            type: string
        both_on:
          - itemid
    events:
      - name: chartevent
        fields:
          subject_id: subject_id
          time: charttime
          code:
            - label
            - valueuom
          numeric_value: valuenum
          text_value: value
          extension:
            hadm_id: hadm_id
            stay_id: stay_id
            row_id: row_id


  - name: icustays
    path: icu/icustays.csv
    fields:
      - field: subject_id
        type: int64
      - field: hadm_id
        type: int64
      - field: stay_id
        type: int64
      - field: row_id
        type: int64
      - field: intime
        type: datetime
      - field: outtime
        type: datetime
      - field: first_careunit
        type: string
      - field: last_careunit
        type: string
      - field: los
        type: float32
      - field: in_code
        type: string
        constant: ICU_ADMISSION
      - field: out_code
        type: string
        constant: ICU_DISCHARGE
      - field: los_code
        type: string
        constant: ICU_LENGTH_OF_STAY
      - field: los_unit
        type: string
        constant: d
    events:
      - name: icu_admission
        fields:
          subject_id: subject_id
          time: intime
          code:
            - in_code
            - first_careunit
          extension:
            hadm_id: hadm_id
            stay_id: stay_id
            row_id: row_id
      - name: icu_discharge
        fields:
          subject_id: subject_id
          time: outtime
          code:
            - out_code
            - last_careunit
          extension:
            hadm_id: hadm_id
            stay_id: stay_id
            row_id: row_id
      - name: icu_length_of_stay
        fields:
          subject_id: subject_id
          time: outtime
          code:
            - los_code
            - los_unit
          numeric_value: los
          extension:
            hadm_id: hadm_id
            stay_id: stay_id
            row_id: row_id
