name: mimic
version: "3.1"
tables:
  - name: medications
    path: icu/inputevents.csv
    fields:
      - field: subject_id
        type: int64
      - field: endtime
        type: datetime
      - field: amount
        type: float32
      - field: amountuom
        type: string
      - field: starttime
        type: datetime
      - field: rateuom
        type: string
      - field: rate
        type: float32
      - field: itemid
        type: int64
    join:
      - name: d_items
        path: icu/d_items.csv
        fields:
          - field: itemid
            type: int64
          - field: label
            type: string
        both_on:
          - itemid
    events:
      - name: dosage
        fields:
          subject_id: subject_id
          time: endtime
          code:
            - label
            - amountuom
          numeric_value: amount
      - name: rate
        fields:
          subject_id: subject_id
          time: starttime
          code:
            - label
            - rateuom
          numeric_value: rate

  - name: chartevents
    path: icu/chartevents.csv
    fields:
      - field: subject_id
        type: int64
      - field: charttime
        type: datetime
      - field: value
        type: string
      - field: valuenum
        type: float32
      - field: valueuom
        type: string
      - field: itemid
        type: int64
    join:
      - name: d_items
        path: icu/d_items.csv
        fields:
          - field: itemid
            type: int64
          - field: label
            type: string
        both_on:
          - itemid
    events:
      - name: chartevent
        fields:
          subject_id: subject_id
          time: charttime
          code:
            - label
            - valueuom
          numeric_value: valuenum
          text_value: value
