name: mimic
version: "3.1"
tables:
  - name: medications
    path: icu/inputevents_small.csv
    fields:
      - field: subject_id
        type: int64
      - field: endtime
        type: datetime
      - field: amount
        type: float32
      - field: amountuom
        type: string
      - field: starttime
        type: datetime
      - field: rateuom
        type: string
      - field: rate
        type: float32
      - field: itemid
        type: int64
    join:
      - name: d_items
        path: icu/d_items.csv
        fields:
          - field: itemid
            type: int64
          - field: label
            type: string
        both_on:
          - itemid
    events:
      - name: dosage
        fields:
          subject_id: subject_id
          time: endtime
          code:
            - label
            - amountuom
          numeric_value: amount
      - name: rate
        fields:
          subject_id: subject_id
          time: starttime
          code:
            - label
            - rateuom
          numeric_value: rate
